# Generated by Django 3.0.4 on 2020-07-25 17:19

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('mobile_numer', models.IntegerField(validators=[authentication.models.validate_mobile_no])),
                ('pincode', models.IntegerField(validators=[authentication.models.validate_pin])),
                ('line', models.TextField()),
                ('landmark', models.CharField(default=None, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
